# Configuration for wp-updater-3.0.0.jar (WorldPainter-Update.exe)
manifestUrl=https://github.com/saplome/WorldPainter-LANGUAGES/releases/latest/download/update-manifest.txt
launch=../WorldPainter Languages.exe
